/*
 * @brief @@OD_NAME@@ OD generated header
 * 
 * @file GeneratedOD.h
 */

#ifndef OSCO_GEN_OD_H
#define OSCO_GEN_OD_H

/* Includes -------------------------------------------- */
@@CUSTOM_OD_DEFINE@@

/* Defines --------------------------------------------- */
/* OD description defines */
#define OD_NAME @@OD_NAME@@
#define OD_SOURCE_FILE @@OD_SOURCE_FILE@@
#define OD_DESCRIPTION @@OD_DESCRIPTION@@

/* OSCO OD Generator defines */
#define OSCO_OD_GEN_VERSION_MAJOR @@OSCO_OD_GEN_VERSION_MAJOR@@
#define OSCO_OD_GEN_VERSION_MINOR @@OSCO_OD_GEN_VERSION_MINOR@@
#define OSCO_OD_GEN_VERSION_REV @@OSCO_OD_GEN_VERSION_REV@@
#define OSCO_OD_GEN_VERSION_STR "@@OSCO_OD_GEN_VERSION_MAJOR@@.@@OSCO_OD_GEN_VERSION_MINOR@@.@@OSCO_OD_GEN_VERSION_REV@@"

/* DeviceInfo defines */
#define VENDOR_NAME @@VENDOR_NAME@@
#define VENDOR_NUMBER @@VENDOR_NUMBER@@
#define PRODUCT_NAME @@PRODUCT_NAME@@
#define PRODUCT_NUMBER @@PRODUCT_NUMBER@@
#define REVISION_NUMBER @@REVISION_NUMBER@@
#define ORDER_CODE @@ORDER_CODE@@
#define BAUDRATE_10   @@BAUDRATE_10@@
#define BAUDRATE_20   @@BAUDRATE_20@@
#define BAUDRATE_50   @@BAUDRATE_50@@
#define BAUDRATE_125  @@BAUDRATE_125@@
#define BAUDRATE_250  @@BAUDRATE_250@@
#define BAUDRATE_500  @@BAUDRATE_500@@
#define BAUDRATE_800  @@BAUDRATE_800@@
#define BAUDRATE_1000 @@BAUDRATE_1000@@
#define SIMPLE_BOOT_UP_MASTER @@SIMPLE_BOOT_UP_MASTER@@
#define SIMPLE_BOOT_UP_SLAVE  @@SIMPLE_BOOT_UP_SLAVE@@
#define GRANULARITY @@GRANULARITY@@
#define DYN_CHANNELS_SUPPORTED @@DYN_CHANNELS_SUPPORTED@@
#define GROUP_MESSAGING @@GROUP_MESSAGING@@
#define LSS_SUPPORTED @@LSS_SUPPORTED@@

/* OD Comments defines */
#define OD_COMMENTS_LINES @@OD_COMMENTS_LINES@@
#define OD_COMMENTS @@OD_COMMENTS@@

/* DummyUsage defines */
#define OD_DUMMY_0001_SUPPORTED @@OD_DUMMY_0001_SUPPORTED@@
#define OD_DUMMY_0002_SUPPORTED @@OD_DUMMY_0002_SUPPORTED@@
#define OD_DUMMY_0003_SUPPORTED @@OD_DUMMY_0003_SUPPORTED@@
#define OD_DUMMY_0004_SUPPORTED @@OD_DUMMY_0004_SUPPORTED@@
#define OD_DUMMY_0005_SUPPORTED @@OD_DUMMY_0005_SUPPORTED@@
#define OD_DUMMY_0006_SUPPORTED @@OD_DUMMY_0006_SUPPORTED@@
#define OD_DUMMY_0007_SUPPORTED @@OD_DUMMY_0007_SUPPORTED@@

/* OD Content defines */
#define OD_OBJECT_COUNT @@OD_OBJECT_COUNT@@
#define OD_RPDO_COUNT @@OD_RPDO_COUNT@@
#define OD_TPDO_COUNT @@OD_TPDO_COUNT@@
#define OD_SDO_SERVER @@OD_SDO_SERVER@@
#define OD_SDO_CLIENT @@OD_SDO_CLIENT@@

#endif /* OSCO_GEN_OD_H */
