version: "3.7"

services:
  osco-od-gen-image:
    image: osco-od-gen-image
    container_name: osco-od-gen-image
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - '../:/repository'
    privileged: true
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
